version: '2'
services:
  chess:
    image: stuartleeks/chesstest
    ports:
     - 80:5000
    environment:
      mongodbConnectionString: mongodb://mongo:27017
      ApplicationInsights__InstrumentationKey: $APPINSIGHTS_KEY
    labels: 
      com.microsoft.acs.dcos.marathon.vhost: dotnetoxford.faux.ninja
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {} # defaults to driver:local
