version: '2'
services:
  chess:
#    image: chesstest  # when built locally
    image: stuartleeks/chesstest  # when pushed to docker hub
    ports: 
     - 80:5000
    environment: 
      mongodbConnectionString: mongodb://mongo:27017
      ApplicationInsights__InstrumentationKey: $APPINSIGHTS_KEY 
  mongo:
    image: mongo
    volumes: 
      - mongo-data:/data/db
      
volumes: 
  mongo-data: {} # defaults to driver:local


    # TODO - mount data in volume so that it persists?!
